Homework JS-part-1
UginB/js-part-1 pull request #1
Opened 2022-12-25 18:09 UTC by UginB

Выполнил домашку:
Расчитать сухопутный маршрут из одной страны в другую с помощью [Rest Countries API](https://restcountries.com/#api-endpoints-v3), сделав минимум запросов. Код должен работать асинхронно через API получения отдельной страны.

Пример:
Вводим Австрию и Болгарию, результат:

Austria → Hungary → Serbia → Bulgaria
Austria → Hungary → Romania → Bulgaria

Понадобилось всего 100500 запросов!

2023-01-06 00:08 UTC, ipetropolsky requested changes

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +async function getCountrieData(cca3, search) {
```suggestion
async function getCountryData(cca3, search) {
```

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +    if (search) {
Какой-то странный параметр :) Можно же просто не вызывать функцию, если не нужно ничего делать.

Если я правильно понял, смысл в остановке других запросов при нахождении маршрута, так? Но те, что уже запустились, не остановишь. А те, что будут запущены, могут проверить этот флаг и не запускаться. Не внутри функции, а снаружи.

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +            error = false;
Ну он и так false ) Лишняя ветка.

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +            output.textContent = 'Начальная и конечная страна совпадают! Введите разные страны для поиска пути!';
На этом бы закончить выполнение этой функции, всё уже ясно и результат есть. А мы ещё кучу кода выполняем, оно точно нужно?

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +        const archive = {};
Всё что ниже не выглядит как часть обработчика submit. Функция обработчика — что-то показать, задизейблить, запустить, раздизейблить. Логику лучше держать отдельно. Потому что появляется вторая кнопка или событие, по которому запускается поиск, а у нас всё в сабмите.

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +        const getBorders = (searchingArr) => {
Переименовать бы так, чтобы было понятно, массив чего это.

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +                                        archive[countryFromBorders] = res;
М.б. `archive[countryFromBorders] = await getCountrieData()`?

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +                });
Сурово ) Ошибки же бывают разные, может быть, можно описать какие-то случаи попонятнее для юзера? Не принципиально.

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +            while (search && countOfAttemps < 10) {
Тут будет бесконечный цикл, если отвалится самый первый запрос.

2023-01-06 00:08 UTC, ipetropolsky commented on index.js
> +                })
Частично дублируется логика из `getBorders`, получится сделать так, чтобы механизм походов и кэширования был один и тот же?

2023-01-06 08:56 UTC, UginB commented on index.js
> +async function getCountrieData(cca3, search) {
опечатался)

2023-01-06 08:58 UTC, UginB commented on index.js
> +    if (search) {
да, забыл переделать этот момент)

2023-01-06 13:27 UTC, UginB commented on index.js
> +                                        archive[countryFromBorders] = res;
Я ниже еще использую res

2023-01-06 13:48 UTC, ipetropolsky commented on index.js
> +                                        archive[countryFromBorders] = res;
Можно использовать там `archive[countryFromBorders]` )  Ладно, не принципиально.

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +    const searchNeighbors = async (cca3, toCountryValue, firstIteration, wayStep) => {
`toCountryValue` → `toCountryCode` наверно.

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +    const createTextElementOutput = (innerText, errorElem) => {
Так погрязнешь в параметрах с каждым новым вариантом вывода. Лучше иметь функции `createText` и `createError` (которые под капотом могут вызывать что-то общее). На заметку, не принципиально.

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +                    `Ошибка со стороны сервера! ${e.message} Попробуйте перезагрузить страницу или зайти позже!`,
Спасите-помогите! Такой тон :)

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +                    for (let i = 1; i < archive[country].borders.length; i++) {
Гораздо удобнее же `forEach`, не? `for` нужен только для супер-оптимизированного кода или если тебе нужно выйти из него где-то посередине с помощью `break`. Не принципиально, просто удобнее.

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +                const nextSearchingArr = [];
Я бы назвал `nextSearchPromises` для ясности.

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +                            countOfRequests += 1;
Я бы перенёс счётчик ближе к запросам, отсюда не видно, сколько там чего вызывается внутри.

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +        }
Тут нужны пояснения.

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +                way.push(wayStep);
Почему-то там всё время первый элемент — пустой объект. И потом ниже в `countryItem` пустой массив.
<img width="748" alt="Screenshot 2023-01-06 at 15 13 23" src="https://user-images.githubusercontent.com/1861705/211029342-9ccfe6c7-8273-4706-9485-7b7c2f54a3f4.png">

2023-01-06 14:16 UTC, ipetropolsky commented on index.js
> +        });
Какой-то прям очень сложный код чтобы сджойнить несколько названий через стрелочку. И сортировка выше, я так и не понял, в чём суть. Может быть, неудобно устроено хранение данных? Давай наверно не будем переделывать уже, если только сам не хочешь разобраться. Но обращай внимание на такие звонки.

2023-01-06 14:43 UTC, UginB commented on index.js
> +        }
в way находятся массивы стран соответствующие количеству шагов от fromCountry до toCountry. Я перебираю по очереди каждый объект от начала пути в конец. Проверяю - какие страны в объекте, граничат с toCountry и отсеиваю их в объект в sortWay. Потом я проверяю следующий объект в way, на предмет наличия стран, которые являются соседями стран в отсортированном ранее объекте в sortWay. И так идя от конца в начало, остаются только страны по которым проходит самый короткий путь. Надеюсь понятно:DDDDDD

2023-01-06 15:17 UTC, UginB commented on index.js
> +        });
Я сообразил только так соединить, сложность в выводе при ситуации, когда какой-то шаг можно сделать через несколько разных стран

2023-01-06 15:19 UTC, UginB commented on index.js
> +                    `Ошибка со стороны сервера! ${e.message} Попробуйте перезагрузить страницу или зайти позже!`,
ахахах) Я не скуплюсь на эмоции

2023-01-06 15:19 UTC, UginB commented on index.js
> +    const searchNeighbors = async (cca3, toCountryValue, firstIteration, wayStep) => {
да, так лучше подойдет

2023-01-07 17:51 UTC, ipetropolsky approved these changes

2023-01-07 17:51 UTC, ipetropolsky commented on index.js
> +            console.log(countryItem);
Опс )

2023-01-08 09:10 UTC, UginB commented on index.js
> +            console.log(countryItem);
Проглядел, ахах

2023-01-08 09:11 UTC, merged